---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.31.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: bufbuild/buf@v1.25.0
- name: protocolbuffers/protobuf-go/protoc-gen-go@v1.31.0
- name: grpc/grpc-go/protoc-gen-go-grpc@cmd/protoc-gen-go-grpc/v1.3.0
- name: grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@v2.16.0
- name: grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2@v2.16.0
- name: dominikh/go-tools/staticcheck@2023.1.3
