---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v3.70.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: bufbuild/buf@v1.8.0
- name: protocolbuffers/protobuf-go/protoc-gen-go@v1.28.1
- name: grpc/grpc-go/protoc-gen-go-grpc@cmd/protoc-gen-go-grpc/v1.2.0
- name: grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@v2.11.3
- name: grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2@v2.11.3
- name: dominikh/go-tools/staticcheck@2022.1
