name: Tidy
on:
  push:
    branches:
    - renovate/*
jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Go Mod Tidy
      uses: at-wat/go-sum-fix-action@v0
      with:
        git_user: github-actions[bot]
        git_email: github-actions[bot]@users.noreply.github.com
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_style: squash
        push: force
